services:
  # ========= MANAGER =========
  opensearch-manager:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch-manager
    environment:
      - cluster.name=siem-cluster
      - node.name=opensearch-manager
      - node.roles=cluster_manager
      - discovery.seed_hosts=opensearch-manager,opensearch-data1,opensearch-data2
      - cluster.initial_cluster_manager_nodes=opensearch-manager,opensearch-data1,opensearch-data2
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile: { soft: 65536, hard: 65536 }
    ports:
      - "9200:9200"
    volumes:
      - ./opensearch-config/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml
    networks:
      - opensearch-net

  # ========= INGEST =========
  opensearch-ingest:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch-ingest
    environment:
      - cluster.name=siem-cluster
      - node.name=opensearch-ingest
      - node.roles=ingest
      - discovery.seed_hosts=opensearch-manager,opensearch-data1,opensearch-data2
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile: { soft: 65536, hard: 65536 }
    volumes:
      - ./opensearch-config/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml
    networks:
      - opensearch-net

  # ========= DATA 1 =========
  opensearch-data1:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch-data1
    environment:
      - cluster.name=siem-cluster
      - node.name=opensearch-data1
      - node.roles=data,cluster_manager
      - discovery.seed_hosts=opensearch-manager,opensearch-data1,opensearch-data2
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - ./opensearch-config/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile: { soft: 65536, hard: 65536 }
    networks:
      - opensearch-net

  # ========= DATA 2 =========
  opensearch-data2:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch-data2
    environment:
      - cluster.name=siem-cluster
      - node.name=opensearch-data2
      - node.roles=data,cluster_manager
      - discovery.seed_hosts=opensearch-manager,opensearch-data1,opensearch-data2
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
      - ./opensearch-config/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile: { soft: 65536, hard: 65536 }
    networks:
      - opensearch-net

  # ========= DASHBOARD =========
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-manager:9200"]'
    depends_on:
      - opensearch-manager
    networks:
      - opensearch-net
    # ========= LOGSTASH =========
  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin@sha256:43b0cdaf26edca812a9eafb684ae6101d8f2fd27165345737c39c04a6c7430eb
    container_name: logstash
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./sensor/threat-intel:/usr/share/logstash/threat-intel:ro
    depends_on:
      - opensearch-ingest
    environment:
      - LOGSTASH_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    networks:
      - opensearch-net

  # ========= ATTACKER =========
  kali-attacker:
    image: kalilinux/kali-rolling
    container_name: kali-attacker
    tty: true # Keep container running
    networks:
      attacker-net:
        ipv4_address: 172.30.10.10
    cap_add:
      - NET_ADMIN
    command: tail -f /dev/null

  # ========= VICTIM (DVWA) =========
  dvwa:
    image: vulnerables/web-dvwa:latest
    container_name: dvwa
    restart: unless-stopped
    networks:
      server-net:
        ipv4_address: 172.30.20.10
    ports:
      - "8080:80"
    cap_add:
      - NET_ADMIN

  # ========= ROUTER =========
  router:
    image: alpine:latest
    container_name: router
    command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      attacker-net:
        ipv4_address: 172.30.10.254
      server-net:
        ipv4_address: 172.30.20.254
    restart: always

volumes:
  opensearch-data1:
  opensearch-data2:


networks:
  opensearch-net:
  attacker-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-attacker-net
    ipam:
      config:
        - subnet: 172.30.10.0/24
  server-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-server-net
    ipam:
      config:
        - subnet: 172.30.20.0/24
