input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  mutate {
    add_field => { "ingest_node" => "opensearch-ingest" }
  }
}

output {
  opensearch {
    hosts => ["https://opensearch-ingest:9200"]
    index => "siem-test-%{+YYYY.MM.dd}"
    user => "admin"
    password => "${LOGSTASH_PASSWORD}"
    ssl => true
    ssl_certificate_verification => false
  }
  stdout { codec => rubydebug }
}
